name: Testing and building
on:
  pull_request:
    branches:
      - '*'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'
      
      - name: Update packages and module
        run: |
          go get -u ./...
          go mod tidy
          go get golang.org/x/tools/cmd/goimports@latest
      
      - name: Install dependencies
        run: go mod tidy
      
      - name: Run testing
        run: go test -race ./...
      
      - name: Build painter
        run: go build -o out/painter cmd/painter/main.go
